### ISSUE TITLE
Strings in Value field

### ISSUE THREAD

**Issue by Brad-Cole** [Xerxes25x/Project#3]
Currently, if a user enters anything other than a number into the Value field a blank entry will be submitted to the database. A dialogue should prompt users to input only a number.

**Comment by Brad-Cole** [comment]
I have solved half of this problem by changing the database entry type to Number for this. 
I have been able to figure out how to get prompts to display but have not been able to get the forms to reset to "Pristine" after the fields are added, updated or cleared. This causes prompts/errors to display when the user hasn't tried to do anything new.

**Comment by cj-taylor** [comment]
Based off your logic [here](https://github.com/Xerxes25x/Project/blob/master/public/index.html#L53) consider `$setUntouched()`

**Comment by Brad-Cole** [comment]
This bug now appears to be fixed by using this setup in the Index.html 
`<form name="myForm3" novalidate="">
              <input name="myValue"class="form-control" type="Number" min="0" ng-model="game.value" required>
</form>
<span class="warning" ng-show="myForm3.myValue.$touched && myForm3.myValue.$invalid">Positive number is required.</span>
`
And then using this in the controller on the relevant buttons:
`$scope.myForm3.$setUntouched();`

A similar variation was used for the other form fields.
