### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by Brad-Cole** [Xerxes25x/Project#4]
A search bar should be implemented to allow searches. The search should check Titles and Systems and perhaps have a field to allow a Value range. My first thought is to implement one similar to how the search works on this project: http://coenraets.org/apps/angular-directory/#/employees

**Comment by cj-taylor** [comment]
Consider use of ng-filter 

https://docs.angularjs.org/api/ng/filter/filter

**Comment by Brad-Cole** [comment]
Got a basic search bar implemented.
