### ISSUE TITLE
Provide Total Value

### ISSUE THREAD

**Issue by Brad-Cole** [Xerxes25x/Project#5]
Providing the total value of the collection is a primary feature needed to make the app useful. Displaying collection value underneath the header is my first thought.

**Comment by cj-taylor** [comment]
Consider using a scoped variable and when you fetch the games, iterate over them adding them to the scoped variable accordingly, then display that value in your html.

**Comment by Brad-Cole** [comment]
Total values is working now and calculating under the main header.
